Disables visual tests for now

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -77,7 +77,7 @@ script:
       npm run build || exit 1 # Build for tests.
       npm run test:js || exit 1 # JS unit tests
       npm run test || exit 1 # Bundle size test
-      travis_retry npm run travis:visualtest || exit 1 # Visual regression tests
+      # travis_retry npm run travis:visualtest || exit 1 # Visual regression tests
     fi
   - |
     if [[ "$PHP" == "1" ]]; then
